# Generated by Django 5.2.3 on 2025-07-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ehrms_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='First', max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(default='Last', max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('institute_name', models.CharField(max_length=255)),
                ('branch', models.TextField(default='Polytechnic', max_length=100)),
                ('designation', models.CharField(max_length=50)),
                ('security_question', models.CharField(choices=[('pet_name', 'What is the name of your first pet?'), ('school_name', 'What is the name of your first school?'), ('birth_city', 'In which city were you born?'), ('best_friend', 'What is the name of your childhood best friend?'), ('favorite_food', 'What is your favorite food?'), ('favorite_book', 'What is your favorite book?'), ('nickname', 'What was your childhood nickname?')], default='pet_name', max_length=50)),
                ('security_answer', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_coordinator', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
