# Generated by Django 5.2.3 on 2025-06-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='institution_name',
            new_name='institute_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='First', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Last', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question',
            field=models.CharField(choices=[('pet_name', 'What is the name of your first pet?'), ('school_name', 'What is the name of your first school?'), ('birth_city', 'In which city were you born?'), ('best_friend', 'What is the name of your childhood best friend?'), ('favorite_food', 'What is your favorite food?'), ('favorite_book', 'What is your favorite book?'), ('nickname', 'What was your childhood nickname?')], default='pet_name', max_length=50),
        ),
    ]
