# Generated by Django 5.2.3 on 2025-08-01 11:54

import Login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=Login.models.user_photo_path),
        ),
    ]
