# Generated by Django 5.2.3 on 2025-06-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_rename_is_staff_user_is_coordinator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
