# Generated by Django 5.2.3 on 2025-07-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
