# Generated by Django 5.2.3 on 2025-07-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Program Name')),
                ('target_group', models.TextField(blank=True, null=True, verbose_name='Target Group')),
                ('venue', models.CharField(blank=True, choices=[('IRDT', 'IRDT'), ('NITTTR Chandigarh', 'NITTTR Chandigarh'), ('NITTTR Bhopal', 'NITTTR Bhopal')], max_length=100, null=True, verbose_name='Venue')),
                ('mode', models.CharField(blank=True, choices=[('Contact', 'Contact'), ('Online', 'Online')], max_length=20, null=True, verbose_name='Mode')),
                ('training_type', models.CharField(blank=True, choices=[('T', 'Training'), ('NT', 'Non-Training')], max_length=5, null=True, verbose_name='Training Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('faculty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Faculty')),
                ('number_of_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='No. of Participants')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remark')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Training Program',
                'verbose_name_plural': 'Training Programs',
                'ordering': ['-start_date'],
            },
        ),
    ]
