# Generated by Django 5.2.3 on 2025-07-18 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Program Name')),
                ('target_group', models.TextField(blank=True, null=True, verbose_name='Target Group')),
                ('venue', models.CharField(blank=True, choices=[('IRDT', 'IRDT'), ('NITTTR Chandigarh', 'NITTTR Chandigarh'), ('NITTTR Bhopal', 'NITTTR Bhopal'), ('IUCTE, Varanasi(UP)', 'IUCTE, Varanasi(UP)'), ('ESTC Ramnagar', 'ESTC Ramnagar'), ('IET, Luckhnow(UP)', 'IET, Luckhnow(UP)'), ('NCB Ballabgarh (Out Station)', 'NCB Ballabgarh (Out Station)')], max_length=100, null=True, verbose_name='Venue')),
                ('mode', models.CharField(blank=True, choices=[('Contact', 'Contact'), ('Online', 'Online')], max_length=20, null=True, verbose_name='Mode')),
                ('training_type', models.CharField(blank=True, choices=[('T', 'Training'), ('NT', 'Non-Training')], max_length=5, null=True, verbose_name='Training Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('faculty_name', models.CharField(blank=True, max_length=150)),
                ('number_of_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='No. of Participants')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remark')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
                ('faculty', models.ForeignKey(blank=True, limit_choices_to={'is_coordinator': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_trainings', to=settings.AUTH_USER_MODEL, verbose_name='Coordinator')),
            ],
            options={
                'verbose_name': 'Training Program',
                'verbose_name_plural': 'Training Programs',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_trainings', to=settings.AUTH_USER_MODEL)),
                ('nominated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominations_made', to=settings.AUTH_USER_MODEL)),
                ('trainee', models.ForeignKey(limit_choices_to={'is_coordinator': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Training.trainingprogram')),
            ],
        ),
    ]
