# Generated by Django 5.2.3 on 2025-07-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='faculty_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
