# Generated by Django 5.2.3 on 2025-07-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0003_rejection_is_read_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rejection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rejection',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='rejection',
            name='trainee',
        ),
        migrations.RemoveField(
            model_name='rejection',
            name='training',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Rejection',
        ),
    ]
