# Generated by Django 5.2.3 on 2025-08-01 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0005_rejection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
