# Generated by Django 5.2.3 on 2025-08-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0006_trainingprogram_finalized_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='edit_request_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='edit_requested',
            field=models.BooleanField(default=False),
        ),
    ]
