# Generated by Django 5.2.3 on 2025-08-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0007_trainingprogram_edit_request_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='edit_request_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('null', 'null')], default='null', max_length=20, null=True),
        ),
    ]
