# Generated by Django 5.2.3 on 2025-08-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0008_alter_trainingprogram_edit_request_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingbatchupload',
            name='session_year',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='trainingbatchupload',
            name='upload_date',
            field=models.DateField(null=True),
        ),
    ]
