# Generated by Django 5.2.3 on 2025-08-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0008_alter_trainingprogram_edit_request_status'),
        ('Training', '0009_trainingbatchupload_session_year_and_more'),
    ]

    operations = [
    ]
