# Generated by Django 5.2.3 on 2025-07-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0002_certificate_uploaded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate_file',
            new_name='file',
        ),
    ]
