# Generated by Django 5.2.3 on 2025-07-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0003_rename_certificate_file_certificate_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='file',
            new_name='certificate_file',
        ),
    ]
