# Generated by Django 5.2.3 on 2025-07-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('nominated', 'Nominated'), ('attended', 'Attended')], default='applied', max_length=20),
        ),
    ]
