# Generated by Django 5.2.3 on 2025-08-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment', '0002_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
