# Generated by Django 5.2.3 on 2025-08-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrollment', '0003_enrollment_finalized_at_enrollment_is_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='notification_read',
            field=models.BooleanField(default=False),
        ),
    ]
