# Generated by Django 5.2.4 on 2025-07-28 06:44

import auth_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=auth_api.models.user_photo_path),
        ),
    ]
